### ISSUE TITLE
Validate local dev env

### ISSUE THREAD

**Issue by drewkhoury** [autocorp/autobot#7]
Follow the "Getting Started" instructions in https://github.com/autocorp/autobot and see how easy/difficult it is to get to a local Hubot terminal.

Hints:
- You can use jeeves or not use jeeves
- You can use 'getting started' or 'hello world' or both

Feedback we're after:
- What bits do/don't make sense
- What level of knowledge have we assumed
- Did you have to do anything outside of the instructions
- Did you know what to do straight away? If you got stuck or tried to jump ahead, where could we improve?

**Comment by nigeldunn** [comment]
I installed autobot last night and then ran the various Jeeves commands. One thing that needs tidying up is that exceptions should be caught and nicer output should be shown. In particular:

```bash
[21:45:46] nigeldunn:autobot git:(master) $ ./bin/jeeves -c

Checking for software dependencies
[ok] ansible v1.9.2
[ok] git v2.3.2
[ok] vboxmanage v4.3.28
[ok] docker v1.5.0
[ok] docker-machine v0.1.0
sh: docker-compose: command not found
Traceback (most recent call last):
  File "./bin/jeeves", line 246, in <module>
    check_requirments()
  File "./bin/jeeves", line 96, in check_requirments
    version_check("docker-compose", "curl -L https://github.com/docker/compose/releases/download/1.1.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose; chmod +x /usr/local/bin/docker-compose")
  File "./bin/jeeves", line 30, in version_check
    software_version = get_version("%s --version" % software)
  File "./bin/jeeves", line 26, in get_version
    return m.group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```

This should (in my opinion) output something like:
```bash
Checking for software dependencies
[ok] ansible v1.9.2
[ok] git v2.3.2
[ok] vboxmanage v4.3.28
[ok] docker v1.5.0
[ok] docker-machine v0.1.0
[missing] docker-compose

To install docker-compose run the following commands:
curl -L https://github.com/docker/compose/releases/download/1.3.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

Curious what others think?

**Comment by drewkhoury** [comment]
Agreed. I'll take a look at this tonight.

**Comment by drewkhoury** [comment]
@nigeldunn for whatever reason github won't let me at mention you in issue #9 so I'll do it here...have raise your bug in the comments above, and fixed it (in develop). It will get marked as closed as soon at it hits master.

**Comment by drewkhoury** [comment]
Improved README.md and Jeeves to better walk first timers through the setup process. It's in dev now https://github.com/autocorp/autobot/tree/develop

**Comment by drewkhoury** [comment]
I'd like to see at least one other pass at this before we mark it as closed. Anyone keen on going through the instructions for creating a dev machine?
