### ISSUE TITLE
Jeeves fails if one of the software packages is missing when running --check

### ISSUE THREAD

**Issue by drewkhoury** [autocorp/autobot#9]
From Nigel...

I installed autobot last night and then ran the various Jeeves commands. One thing that needs tidying up is that exceptions should be caught and nicer output should be shown. In particular:

```bash
[21:45:46] nigeldunn:autobot git:(master) $ ./bin/jeeves -c

Checking for software dependencies
[ok] ansible v1.9.2
[ok] git v2.3.2
[ok] vboxmanage v4.3.28
[ok] docker v1.5.0
[ok] docker-machine v0.1.0
sh: docker-compose: command not found
Traceback (most recent call last):
  File "./bin/jeeves", line 246, in <module>
    check_requirments()
  File "./bin/jeeves", line 96, in check_requirments
    version_check("docker-compose", "curl -L https://github.com/docker/compose/releases/download/1.1.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose; chmod +x /usr/local/bin/docker-compose")
  File "./bin/jeeves", line 30, in version_check
    software_version = get_version("%s --version" % software)
  File "./bin/jeeves", line 26, in get_version
    return m.group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```

This should (in my opinion) output something like:
```bash
Checking for software dependencies
[ok] ansible v1.9.2
[ok] git v2.3.2
[ok] vboxmanage v4.3.28
[ok] docker v1.5.0
[ok] docker-machine v0.1.0
[missing] docker-compose

To install docker-compose run the following commands:
curl -L https://github.com/docker/compose/releases/download/1.3.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

**Comment by drewkhoury** [comment]
Updates now in develop.

If you have all packages you can edit jeeves on line 107 with `version_check("foo", "bar")`.

You can change `if e.errno != os.errno.ENOENT:` `if e.errno != os.errno.ENOENT:` in jeeves on line 29 to see what an unhanded exception will look like.
